### ISSUE TITLE
MKS-TB67S109-OC : How to interface with 3.3V logic level

### ISSUE THREAD

**Issue by RepRapThailand** [makerbase-mks/MKS-Big-Current-Driver#3]
Hi, 

I try with Arduino UNO and can spin motor but when I try with STM32F103 the motor did not spin.

 Best Regards,

 
![6106](https://user-images.githubusercontent.com/15525407/110646670-b04afe80-81e9-11eb-8d3e-df3f653cc8b0.jpg)

**Comment by mks-viva** [comment]
![image](https://user-images.githubusercontent.com/16629551/128595559-e1e0311e-044f-45f3-be68-779131f94cc0.png)
